README-zh.md
=> 修改README错别字

Dockerfile.apline
=> 提供alpine基建的Dockerfile

backend/utils/chan_test.go
Add Unit Test for backend/utils/chan.go
=> Add Unit Test for backend/utils/chan.go

.gitignore, backend/go.sum, backend/routes/spider.go
=> fix tmp 目录没有提前创建报错的问题

backend/utils/file_test.go, backend/utils/model_test.go, backend/utils/user_test.go
Complete Unit Test for package utils
=> Develop-Complete Unit Test for package utils

backend/database/mongo_test.go
bug fix: fixed mongo.go unit test
=> bug fix: fixed mongo.go unit test

backend/database/mongo_test.go, backend/routes/node_test.go
=> Add unit test for routes/node

backend/services/spider.go
Code optimization:change the crawler zip file to slice read
=> Code optimization:change the crawler zip file to slice read

backend/mock/base.go, backend/mock/file.go, backend/mock/node.go, backend/mock/node_test.go, backend/mock/schedule.go, backend/mock/schedule_test.go, backend/mock/spider.go, backend/mock/system.go, backend/mock/task.go, backend/mock/user.go, backend/mock/utils.go
=> modify unit test to use mock

backend/mock/node_test.go, backend/mock/stats.go, backend/mock/stats_test.go
=> unit test for stats.go

backend/mock/node.go, backend/mock/node_test.go, backend/mock/schedule_test.go, backend/mock/task.go, backend/mock/task_test.go
=> Add unit test for task.go

backend/database/pubsub.go
bug fix: fix redis connection dead cycle
=> bug fix: fix redis connection dead cycle

backend/database/pubsub.go
fix redis connection dead cycle and remove redundant code
=> remove redundant code

backend/database/pubsub.go
hot fix:fix redis lose connection problem
=> hot fix:fix redis lose connection problem

backend/services/spider.go
bug fix:fix permission bug when create spiders dir caused by umask
=> bug fix:fix permission bug when create spiders dir caused by umask

backend/mock/spider.go, backend/mock/spider_test.go
add unit test for routes/spider.go
=> add unit test for routes/spider.go

backend/config/config_test.go
bug fix: fix test failed for config.go
=> bug fix: fix test failed for config.go

backend/services/log.go
bug fix: hot fix out of memory problem caused by log read
=> bug fix: hot fix out of memory problem caused by log read

backend/conf/config.yml, backend/main.go, backend/services/log.go, backend/services/log_test.go
Add delete log files periodically and this function is optional to config config.yml.
=> Add delete log files periodically

backend/main.go, backend/middlewares/auth.go, frontend/src/api/request.js, frontend/src/store/modules/task.js, frontend/src/views/task/TaskDetail.vue, frontend/src/views/task/TaskList.vue
Backend:   
1.[improve]
使用gin提供的RouteGroup功能简化中间件逻辑
2.[break change]
移除Authorization Middleware中对登录注册下载特殊处理逻辑
3.[unsafe problem]
下载任务csv增加登录验证
Frontend:
1. 更改csv下载方式
2. task list页面table section 移除固定width设置,采用自适应,防止大屏空白断裂问题
=> Some Change.

backend/go.mod, backend/go.sum, backend/lib/validate_bridge/validator.go, backend/main.go
Backend:  
upgrade gin framework depend validator version : v8 -> v9
=>  upgrade validate v8 to v9

frontend/src/api/request.js, frontend/src/i18n/zh.js, frontend/src/router/index.js, frontend/src/views/node/NodeList.vue, frontend/src/views/schedule/ScheduleList.vue
1. Fix Some I18n Warning.
2. Fix Navigation Duplicated Error When Current Route Path is `/login`.
3. Fix  Parent Level Named Route Warning.
4. Change `request` function From Promise Syntax To Await/Async.
=> Some Improve Fronted Work.

backend/services/log.go, backend/services/log_test.go
- bug fix:fix read log file oom 
- add unit test for GetLocalLog
=> bug fix:fix read log file oom

backend/database/mongo.go, backend/database/pubsub.go, backend/database/redis.go, backend/services/log.go, backend/services/node.go, backend/services/spider.go, backend/services/system.go, backend/services/task.go, backend/utils/file.go
backend: 
1. Mongo dial add 5 seconds connection timeout.
2. Redis uses connection pool mode.
3. Redis pool new connection have 10 seconds write timeout and read timeout and connection timeout.
=> add timeout and pool

backend/mock/node_test.go, backend/utils/file_test.go
bug fix:fix go test ./..  to pass
=> bug fix:fix go test ./.. 

backend/constants/errors.go, backend/errors/errors.go, backend/services/context/context.go
feat(backend): add some feat for error message system
errors support custom http code and support return invalidated error
=> feat(backend): add some feat for error message system

backend/services/task.go
bug fix:fix data race caused by LockList in issue [#188](https://github.com/crawlab-team/crawlab/issues/188)
=> bug fix:fix data race caused by LockList

backend/main.go
1.support server graceful down
=> feat(backend): support server graceful down

backend/database/pubsub.go, backend/database/redis.go, backend/errors/errors.go, backend/lib/cron/cron_test.go, backend/lib/cron/logger.go, backend/lib/cron/option_test.go, backend/lib/cron/parser_test.go, backend/lib/cron/spec.go, backend/mock/node.go, backend/model/log.go, backend/model/node.go, backend/model/spider.go, backend/services/context/context.go, backend/services/log.go, backend/services/log_test.go, backend/services/msg_handler/msg_log.go, backend/services/msg_handler/msg_system_info.go, backend/services/node.go, backend/services/spider.go, backend/services/spider_handler/spider.go, backend/services/task.go, backend/services/user.go, backend/utils/file.go, backend/utils/file_test.go, backend/utils/helpers.go, backend/utils/model.go, backend/utils/user.go
remove redundant code and some code refactor
=> refactor(all): refactor code

docker_init.sh
=> Fix environment variable replacement for CRAWLAB_API_ADDRESS

frontend/package.json, frontend/src/components/ScrollView/LogItem.vue, frontend/src/components/ScrollView/LogView.vue, frontend/yarn.lock
=> 任务日志ANSI格式化显示

backend/services/register/register.go
fix data race because of register solve issue https://github.com/crawlab-team/crawlab/issues/308
=> bug fix register.go

backend/services/task.go
=> Add return 

backend/conf/config.yml, backend/main.go
=>  修改isDeletePeriodically参数默认为N

backend/main.go, backend/model/task.go, backend/routes/task.go, backend/services/log.go
新增authGroup.DELETE("/tasks_by_status", routes.DeleteTaskByStatus) 支持批量删除指定状态的任务
TaskListRequestData中增加Status字段，支持根据task状态进行筛选
提供接口解决 https://github.com/crawlab-team/crawlab/issues/341
=> 支持批量删除、筛选指定状态的任务

backend/mock/schedule.go, backend/mock/schedule_test.go
=> Update test cases

backend/services/log.go
=> remove  break in select

backend/conf/config.yml, backend/main.go, backend/routes/version.go
=> Add API GetVersion

backend/services/node.go, backend/utils/helpers.go
- Attemp to solve duplicate node register.
=> 尝试解决节点重复注册问题

backend/model/node.go
临时解决修复偶发mongo多节点信息的问题，后续需重构
fix: #391
=> fix(backend):

.gitattributes
=> fix language show

backend/utils/chan.go
- bug fix: fix concurrent map write error
- fix https://github.com/crawlab-team/crawlab/issues/515 and https://github.com/crawlab-team/crawlab/issues/565
=> bug fix: fix concurrent map write error

backend/model/node.go
=> fixed GetNodeBaseInfo

backend/services/task.go
=> bug fix: fix es bug

backend/routes/action.go, backend/routes/config_spider.go, backend/routes/project.go, backend/routes/spider.go, backend/routes/user.go
=> fix miss-return

backend/lib/validate/mongo.go, backend/main.go
=> add mongo objectId  validation

backend/database/redis.go, backend/model/config_spider/scrapy.go
start next stage only if url is not empty
=> fix: start next stage only if url is not empty

backend/services/git.go, backend/template/spiders/segmentfault_colly/go.sum
Signed-off-by: hantmac <hantmac@outlook.com>
=> fix GetGitRemoteBranchesPlain when git url has port

backend/database/redis.go
Signed-off-by: hantmac <hantmac@outlook.com>
support redis password contains special char
fix https://github.com/crawlab-team/crawlab/issues/820
=> support redis password contains special char

backend/services/git.go
Signed-off-by: hantmac <hantmac@outlook.com>
fix git has port
=> fix git has port

backend/routes/schedule.go
=> fixed:#830

README-zh.md, README.md
=> 修复导航连接中的文档链接

k8s/crawlab-master.yaml, k8s/crawlab-worker.yaml
update k8s deploy and docker images.
=> update k8s deploy yaml

workspace/dockerfiles/golang/Dockerfile
rm unused tar to reduce image size
=> build(golang/dockerfile):  rm unused tar

frontend/package.json
https://github.com/crawlab-team/crawlab/issues/1201
=> fix(git): unable to pull code from remote

README-zh.md, README.md
1. branch name has changed to main
2. Docker badge svg link
=> fix(doc): fix some broken links

backend/go.mod, backend/go.sum, frontend/package.json, frontend/pnpm-lock.yaml
https://github.com/crawlab-team/crawlab/issues/1258
=> chore: updated deps

backend/go.mod, backend/go.sum
https://github.com/crawlab-team/crawlab/issues/1221
=> fix: restart command misaligned issue
